---
# RPMs to be installed from the base CentOS repo.
packages:
# Base
- atlas  
- cmake  
- fuse  
- fuse-libs  
- glibc-devel.i686
- glpk  
- lua  
- lua-devel  
- ocaml  
- ocaml-camlp4  
- ocaml-labltk  
- opencv  
- opencv-devel  
- opencv-python  
- perl-Error  
- python-crypto  
- R  
- sqlite  
- xmlrpc-c-devel  
# Exists in EPEL/Base, but more recent version exists elsewhere.
- git  
- subversion

# yum groups to be installed.
yumgroups:
- Additional Development
- Base
- Compatibility libraries
- Console internet tools
- Development tools
- Emacs
- Java Platform
- Legacy UNIX compatibility
- MySQL Database client
- MySQL Database server
- Networking Tools
- PHP Support
- Performance Tools
- Perl Support
- PostgreSQL Database client
- PostgreSQL Database server
- Ruby Support
- Scientific support
- Server Platform
- Server Platform Development
- Web Server
- Web Servlet Engine
